import type { Metadata } from 'next';
import { Gluten } from 'next/font/google';
import './globals.css';
import { FirebaseProvider } from './firebase/FirebaseProvider';

const gluten = Gluten({
	variable: '--font-gluten',
	subsets: ['latin'],
	weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={`${gluten.variable} antialiased`}>
				<FirebaseProvider>
					<div className='flex w-full bg-slate-900 text-white min-h-screen'>{children}</div>
				</FirebaseProvider>
			</body>
		</html>
	);
}
