import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import './globals.css';
import { FirebaseProvider } from './firebase/FirebaseProvider';

// Configure the Montserrat font
const montserrat = Montserrat({
	subsets: ['latin'],
	display: 'swap', // Recommended for font loading strategy
	variable: '--font-montserrat',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={`${montserrat.className} ${montserrat.variable} antialiased`}>
				<FirebaseProvider>
					<div className='flex w-full bg-slate-900 text-white min-h-screen'>{children}</div>
				</FirebaseProvider>
			</body>
		</html>
	);
}
